/**
 * Daily Parallel - "Today in Biblical History" data
 * 366 entries (one per day of year), connecting dates to biblical events,
 * early church history, or seasonal faith observations.
 *
 * Each entry has a day-of-year index (1-366) and a short one-liner.
 * Entries are historically grounded where possible.
 */

export interface DailyParallelEntry {
  day: number; // 1-366, day of year
  text: string;
}

// Helper: get the day-of-year (1-based)
export function getDayOfYear(): number {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  return Math.floor(diff / (1000 * 60 * 60 * 24));
}

export function getTodaysParallel(): DailyParallelEntry {
  const day = getDayOfYear();
  // Wrap around for leap years
  const index = ((day - 1) % DAILY_PARALLELS.length);
  return DAILY_PARALLELS[index];
}

export const DAILY_PARALLELS: DailyParallelEntry[] = [
  // -- January (days 1-31) --
  { day: 1, text: 'On the eighth day, Jewish boys received circumcision and their name — a sign of covenant identity.' },
  { day: 2, text: 'The early church father Basil of Caesarea, champion of Trinitarian theology, died on this day in 379 AD.' },
  { day: 3, text: 'Winter was a time of gathering around hearth fires. The Psalms speak of God as warmth and refuge in every season.' },
  { day: 4, text: 'Around this date in 1785, the first Sunday school classes spread across England, teaching children to read Scripture.' },
  { day: 5, text: 'In ancient Israel, the month of Tevet brought the coldest rains. Ezra 10:9 describes the people "trembling because of the rain."' },
  { day: 6, text: 'Epiphany — the Western church remembers the Magi arriving in Bethlehem, guided by a star to worship the newborn King.' },
  { day: 7, text: 'The Ethiopian church celebrates Christmas (Genna) around this date, one of the oldest Christian traditions in the world.' },
  { day: 8, text: 'In the early church, new converts baptized at Epiphany wore white garments for eight days as a sign of new life.' },
  { day: 9, text: 'The apostle Paul spent winters in various port cities, using the time to write letters that became Scripture.' },
  { day: 10, text: 'Gregory of Nyssa, an early church father who shaped our understanding of the Trinity, is remembered around this time.' },
  { day: 11, text: 'In ancient Judea, winter wheat was sown in the fields. Jesus would later use wheat and harvest as parables of the Kingdom.' },
  { day: 12, text: 'The Dead Sea Scrolls, discovered in 1947, confirmed that Old Testament texts were faithfully preserved for over a thousand years.' },
  { day: 13, text: 'Hilary of Poitiers, who defended the deity of Christ against Arianism, is commemorated around this date.' },
  { day: 14, text: 'The early church in Rome gathered in house churches during winter, sharing meals and breaking bread together.' },
  { day: 15, text: 'Around this time of year, the Sea of Galilee is at its fullest from winter rains — the same sea Jesus calmed with a word.' },
  { day: 16, text: 'The desert monks of Egypt spent winter months copying manuscripts, preserving Scripture through the centuries.' },
  { day: 17, text: 'Anthony of Egypt, the father of Christian monasticism, retreated to the desert around 270 AD to seek God in solitude.' },
  { day: 18, text: 'The Week of Prayer for Christian Unity begins today, a tradition started in 1908 calling believers to pray for the Church.' },
  { day: 19, text: 'In the ancient Near East, January storms reminded Israel of God\'s power over creation described in Job 38.' },
  { day: 20, text: 'Fabian, bishop of Rome, was chosen when a dove landed on his head during the election — reminiscent of Jesus\' baptism.' },
  { day: 21, text: 'Agnes of Rome, a young Christian martyr during the Diocletian persecution, is remembered for her courageous faith.' },
  { day: 22, text: 'Vincent of Saragossa, one of the most venerated early martyrs of Spain, bore witness under Emperor Diocletian.' },
  { day: 23, text: 'The almond tree is the first to blossom in Israel. Jeremiah 1:11-12 uses it as a sign that God watches over His word.' },
  { day: 24, text: 'Francis de Sales, known for his gentle pastoral approach, wrote that "a spoonful of honey catches more flies than a barrel of vinegar."' },
  { day: 25, text: 'The conversion of the apostle Paul on the road to Damascus transformed the greatest persecutor into the greatest missionary.' },
  { day: 26, text: 'Timothy and Titus, Paul\'s faithful companions, carried letters and planted churches across Asia Minor.' },
  { day: 27, text: 'John Chrysostom, whose name means "golden-mouthed," preached so powerfully that crowds in Constantinople were moved to reform.' },
  { day: 28, text: 'Thomas Aquinas, the medieval theologian, taught that faith and reason are complementary paths to understanding God.' },
  { day: 29, text: 'In Israel, the latter rains of winter were essential for the spring harvest — a biblical metaphor for spiritual renewal.' },
  { day: 30, text: 'The Three Holy Hierarchs — Basil, Gregory, and Chrysostom — shaped how the church understands theology and worship.' },
  { day: 31, text: 'John Bosco dedicated his life to educating poor youth in Turin, believing every young person has potential for greatness.' },

  // -- February (days 32-59/60) --
  { day: 32, text: 'Brigid of Kildare, one of Ireland\'s patron saints, founded monasteries that became centers of learning and hospitality.' },
  { day: 33, text: 'The Presentation of Jesus at the Temple: Simeon and Anna recognized the infant as "a light for revelation to the Gentiles."' },
  { day: 34, text: 'Ansgar, the "Apostle of the North," brought the gospel to Scandinavia in the 9th century despite fierce opposition.' },
  { day: 35, text: 'Agatha of Sicily, martyred around 251 AD, became one of the most venerated female saints in the early church.' },
  { day: 36, text: 'Paul Miki and companions were martyred in Nagasaki in 1597, among the first Christian martyrs in Japan.' },
  { day: 37, text: 'In the agricultural calendar of ancient Israel, farmers began preparing fields for the spring barley harvest.' },
  { day: 38, text: 'Jerome, who translated the Bible into Latin (the Vulgate), spent decades in Bethlehem working on the text.' },
  { day: 39, text: 'The Didache, one of the earliest Christian documents outside the New Testament, instructed new believers in prayer and fasting.' },
  { day: 40, text: 'Scholastica, sister of Benedict, is remembered for her deep devotion to prayer and the contemplative life.' },
  { day: 41, text: 'Our Lady of Lourdes is remembered today — a reminder that God often works through humble and unexpected places.' },
  { day: 42, text: 'In the Roman Empire, February was a time of purification rituals. The early church transformed these into seasons of spiritual renewal.' },
  { day: 43, text: 'Around this time, almond blossoms appear across the hills of Judea — the first sign that winter is yielding to spring.' },
  { day: 44, text: 'Cyril and Methodius created the Slavic alphabet to translate Scripture, bringing the Bible to millions in their own language.' },
  { day: 45, text: 'The early Christians in Antioch were the first to be called "Christians" — a name that has endured for two thousand years.' },
  { day: 46, text: 'Around this time of year, the Israelites would have begun preparing for Passover, still weeks away but already on the horizon.' },
  { day: 47, text: 'In the catacombs of Rome, early Christians painted fish, anchors, and good shepherds — symbols of faith under persecution.' },
  { day: 48, text: 'Martin Luther nailed his 95 Theses to the Wittenberg door, but it was his translation of the Bible into German that changed history.' },
  { day: 49, text: 'Polycarp, bishop of Smyrna and student of the apostle John, was martyred around 155 AD, saying "Eighty-six years I have served Him."' },
  { day: 50, text: 'The Chair of Peter is commemorated — a reminder of Jesus\' words: "On this rock I will build my church."' },
  { day: 51, text: 'Irenaeus of Lyon fought against Gnostic heresies, insisting that God created the material world and called it good.' },
  { day: 52, text: 'The apostle Matthias was chosen to replace Judas, reminding us that God fills every vacancy in His plan.' },
  { day: 53, text: 'In ancient Israel, the winter barley crop was crucial for the firstfruits offering at the Temple during Passover.' },
  { day: 54, text: 'The early church in Corinth struggled with divisions — Paul\'s letters remind us that unity in Christ transcends preferences.' },
  { day: 55, text: 'Around this time, shepherds in the Judean hills began moving flocks to new pastures as winter grass sprouted.' },
  { day: 56, text: 'Gabriel, the archangel who announced the births of John and Jesus, appears only four times in Scripture — each time with pivotal news.' },
  { day: 57, text: 'The Waldensians, a pre-Reformation movement in the Alps, preserved vernacular Scripture centuries before the printing press.' },
  { day: 58, text: 'Oswald of Worcester, a 10th-century bishop, was known for washing the feet of the poor every day during Lent.' },
  { day: 59, text: 'In leap years, this extra day reminds us that God is Lord over time itself — "With the Lord a day is like a thousand years."' },

  // -- March (days 60-90) --
  { day: 60, text: 'David, patron saint of Wales, told his followers: "Do the little things." Faithfulness in small matters honors God.' },
  { day: 61, text: 'John Wesley, founder of Methodism, rode over 250,000 miles on horseback to preach the gospel across England.' },
  { day: 62, text: 'In the land of Israel, the spring wildflowers Jesus called "lilies of the field" begin to bloom across the hillsides.' },
  { day: 63, text: 'Casimir of Poland, known for his devotion to the poor, reminds us that royal power is best used in humble service.' },
  { day: 64, text: 'The early church met for worship before dawn on Sundays to celebrate the resurrection before the workday began.' },
  { day: 65, text: 'Perpetua and Felicity were martyred in Carthage in 203 AD — a noblewoman and her slave, united by faith.' },
  { day: 66, text: 'Around this time, the latter rains fall in Israel, fulfilling Joel 2:23: "He has given you the autumn and spring rains."' },
  { day: 67, text: 'Thomas Aquinas once said that all of his writings seemed "like straw" compared to what God had revealed to him in prayer.' },
  { day: 68, text: 'John of God founded a hospital in Granada, pioneering Christian care for the sick and mentally ill.' },
  { day: 69, text: 'Frances of Rome served the poor while managing her household, showing that sacred and daily life are not separate.' },
  { day: 70, text: 'The Forty Martyrs of Sebaste, Roman soldiers who chose death over denying Christ, stood firm in freezing cold around 320 AD.' },
  { day: 71, text: 'The early church in Jerusalem shared all things in common — "there were no needy persons among them" (Acts 4:34).' },
  { day: 72, text: 'Gregory the Great, pope and church reformer, called himself "servant of the servants of God" — a title popes still use.' },
  { day: 73, text: 'Around this time, the Jordan River swells with winter runoff — the same river where Israel crossed into the Promised Land.' },
  { day: 74, text: 'The early church in Antioch was known for their generosity during famine, sending aid to believers in Jerusalem.' },
  { day: 75, text: 'Patrick of Ireland used the shamrock to explain the Trinity — one God in three persons, simple enough for anyone to grasp.' },
  { day: 76, text: 'Cyril of Jerusalem prepared catechumens for baptism with careful teaching, knowing faith requires understanding.' },
  { day: 77, text: 'Joseph, earthly father of Jesus, is honored as a man of quiet obedience who trusted God\'s plan despite not understanding it all.' },
  { day: 78, text: 'The spring equinox approaches — ancient Israel tied their calendar to agricultural and astronomical cycles ordained by God.' },
  { day: 79, text: 'The Benedictine motto "Ora et Labora" (pray and work) shaped Western civilization\'s understanding of productive faith.' },
  { day: 80, text: 'Around this time, the barley harvest in Israel begins to ripen — the crop used for the Passover firstfruits offering.' },
  { day: 81, text: 'Nicholas von Flue, a Swiss hermit and peacemaker, helped prevent civil war through prayer and counsel.' },
  { day: 82, text: 'The Annunciation approaches — Gabriel told Mary, "Nothing will be impossible with God," and she replied, "Let it be."' },
  { day: 83, text: 'Oscar Romero, archbishop of San Salvador, was martyred in 1980 while celebrating Mass, standing for justice and the poor.' },
  { day: 84, text: 'The Annunciation: the angel Gabriel visited Mary in Nazareth, and the Word began to dwell among us.' },
  { day: 85, text: 'In early spring, fig trees in Israel begin to show their first buds — Jesus used the fig tree as a sign of the times.' },
  { day: 86, text: 'The early church sang hymns drawn from the Psalms, establishing a tradition of corporate worship through song.' },
  { day: 87, text: 'Around this date, families in ancient Israel began cleaning their homes of leaven in preparation for Passover.' },
  { day: 88, text: 'The church fathers debated the date of Easter for centuries, settling on the first Sunday after the spring full moon.' },
  { day: 89, text: 'Eusebius of Caesarea wrote the first comprehensive history of the church, preserving stories that would otherwise be lost.' },
  { day: 90, text: 'As March ends, the land of Israel is vivid green — a brief window before the summer heat dries the hillsides.' },

  // -- April (days 91-120) --
  { day: 91, text: 'Hugh of Grenoble supported the founding of the Carthusian order, dedicated to silence, prayer, and solitude.' },
  { day: 92, text: 'Francis of Paola established the Minims, an order devoted to humility and fasting as spiritual disciplines.' },
  { day: 93, text: 'Around this time, Passover lambs were selected in ancient Israel — four days before the feast, as described in Exodus 12.' },
  { day: 94, text: 'Isidore of Seville compiled an encyclopedia of all human knowledge, believing learning glorifies the Creator.' },
  { day: 95, text: 'Vincent Ferrer traveled across Europe preaching repentance, drawing thousands to faith through his fiery sermons.' },
  { day: 96, text: 'In Israel, the wheat harvest follows the barley — a progression reflected in the counting of the Omer to Pentecost.' },
  { day: 97, text: 'Jean-Baptiste de La Salle founded schools for the poor, insisting that education is a path to dignity and faith.' },
  { day: 98, text: 'The early church remembered that Jesus washed the disciples\' feet before His crucifixion — a model of servant leadership.' },
  { day: 99, text: 'Dietrich Bonhoeffer was executed on this date in 1945 for his role in resisting tyranny, having written that "cheap grace is the enemy of the church."' },
  { day: 100, text: 'William of Ockham taught that the simplest explanation is often the best — a principle he rooted in the clarity of divine creation.' },
  { day: 101, text: 'Stanislaus of Krakow, martyred by a king he rebuked, exemplified the prophetic tradition of speaking truth to power.' },
  { day: 102, text: 'Around this time, pilgrims in ancient Israel would begin their journey to Jerusalem for the spring feasts.' },
  { day: 103, text: 'Martin I, bishop of Rome, was exiled for his theological convictions — a reminder that faithfulness has a cost.' },
  { day: 104, text: 'The early church debated whether Gentile believers needed to follow Jewish law — the Jerusalem Council (Acts 15) settled the question.' },
  { day: 105, text: 'Damien of Molokai served lepers in Hawaii for sixteen years, eventually contracting the disease himself.' },
  { day: 106, text: 'In the spring, the Mediterranean world came alive with trade and travel — Paul used these routes to spread the gospel.' },
  { day: 107, text: 'The road to Emmaus: two disciples walked with the risen Jesus without recognizing Him until He broke bread.' },
  { day: 108, text: 'Anselm of Canterbury wrote "I believe in order to understand," framing faith as the foundation for all knowledge.' },
  { day: 109, text: 'George, patron of England, is remembered not for slaying a dragon but for his steadfast faith unto martyrdom.' },
  { day: 110, text: 'Fidelis of Sigmaringen, a lawyer turned Capuchin friar, gave away his possessions to serve the poor.' },
  { day: 111, text: 'Mark the Evangelist is traditionally credited with founding the church in Alexandria, one of early Christianity\'s great centers.' },
  { day: 112, text: 'Around this time, the wheat in Israel\'s fields stands tall and green — the harvest Jesus foresaw in John 4:35.' },
  { day: 113, text: 'Zita of Lucca, a domestic servant, was known for giving her own food to the poor — living out James 2:15-16 daily.' },
  { day: 114, text: 'Peter Chanel was martyred in Oceania in 1841, one of the first Christian missionaries to the Pacific Islands.' },
  { day: 115, text: 'Catherine of Siena, a Doctor of the Church, wrote letters to popes and princes calling for reform and faithfulness.' },
  { day: 116, text: 'Pius V reformed the Roman liturgy and promoted education, believing that worship should be accessible to all believers.' },
  { day: 117, text: 'Joseph the Worker is honored — a carpenter\'s hands shaped the wood that sheltered the Son of God.' },
  { day: 118, text: 'Athanasius of Alexandria stood contra mundum ("against the world") to defend the full divinity of Christ.' },
  { day: 119, text: 'Philip and James, apostles of Christ, carried the gospel to distant lands, rarely receiving credit in history books.' },
  { day: 120, text: 'Around this time, the church celebrates Rogation Days — prayer walks through fields asking God\'s blessing on the harvest.' },

  // -- May (days 121-151) --
  { day: 121, text: 'Gothard of Hildesheim was a bishop known for personally building churches and schools across his diocese.' },
  { day: 122, text: 'The early Celtic Christians built stone beehive huts on remote islands, seeking God in the wind and waves.' },
  { day: 123, text: 'Around this time, the wheat harvest begins in the lowlands of Israel — Pentecost (Shavuot) is the feast of firstfruits.' },
  { day: 124, text: 'Florian of Lorch, a Roman officer martyred for his faith, became the patron of those who fight fires — both literal and spiritual.' },
  { day: 125, text: 'Hilary of Arles presided over church councils that shaped how the early church governed itself and resolved disputes.' },
  { day: 126, text: 'The Ascension approaches — Jesus promised, "I am with you always, to the end of the age," before returning to the Father.' },
  { day: 127, text: 'In the upper room, 120 believers waited in prayer for the Holy Spirit. Patience in prayer precedes power in mission.' },
  { day: 128, text: 'Julian of Norwich wrote "All shall be well" during a time of plague and war — radical trust in God\'s goodness.' },
  { day: 129, text: 'Around this time, the apostles in Jerusalem prayed together daily in the Temple courts, still faithful to their Jewish roots.' },
  { day: 130, text: 'Damien of Belgium is remembered for bringing healing and dignity to the outcasts on the island of Molokai.' },
  { day: 131, text: 'Matthias replaced Judas among the Twelve — God wastes nothing, not even betrayal, in building His Kingdom.' },
  { day: 132, text: 'Nereus and Achilleus, Roman soldiers who converted to Christianity, laid down their weapons and took up the cross.' },
  { day: 133, text: 'Our Lady of Fatima is remembered — three shepherd children in Portugal reported visions calling for prayer and penance.' },
  { day: 134, text: 'Matthias was chosen by lot in Acts 1:26 — a reminder that God\'s providence works even through seemingly random events.' },
  { day: 135, text: 'Isidore the Farmer prayed while he plowed, teaching that ordinary work done with devotion is a form of worship.' },
  { day: 136, text: 'Around this time, Pentecost is celebrated — the Spirit descended like fire, and the church was born in power and diversity.' },
  { day: 137, text: 'At Pentecost, people from every nation heard the gospel in their own language — God speaks to every culture.' },
  { day: 138, text: 'John I, bishop of Rome, traveled to Constantinople seeking peace between churches — an early ecumenical effort.' },
  { day: 139, text: 'Eric IX of Sweden promoted Christianity through just governance rather than force, an unusual approach for his time.' },
  { day: 140, text: 'Bernardino of Siena preached in public squares, reaching people where they gathered rather than waiting for them in church.' },
  { day: 141, text: 'The early church father Tertullian wrote, "The blood of the martyrs is the seed of the church."' },
  { day: 142, text: 'Rita of Cascia, known as the patron of impossible causes, endured extraordinary suffering with persistent faith.' },
  { day: 143, text: 'Around this time, the dry season begins in Israel. The Psalmist\'s cry "my soul thirsts for you" takes on visceral meaning.' },
  { day: 144, text: 'The Venerable Bede, an English monk, wrote the first history of England and translated the Gospel of John on his deathbed.' },
  { day: 145, text: 'Gregory VII reformed the medieval church, insisting that spiritual authority must not be bought or sold.' },
  { day: 146, text: 'Philip Neri, the "Apostle of Rome," used humor, joy, and music to draw people back to faith in a cynical age.' },
  { day: 147, text: 'Augustine of Canterbury brought the gospel to Anglo-Saxon England in 597 AD, beginning the Christianization of Britain.' },
  { day: 148, text: 'Around this date, the early summer heat in the Near East drove travelers to rest during midday — Jesus met the Samaritan woman at such an hour.' },
  { day: 149, text: 'Paul VI embraced ecumenism at the Second Vatican Council, seeking greater unity among all Christians.' },
  { day: 150, text: 'Joan of Arc, burned at the stake at age 19, heard voices calling her to courage — "I am not afraid; I was born to do this."' },
  { day: 151, text: 'The Visitation: Mary traveled to see Elizabeth, and the child in Elizabeth\'s womb leaped for joy at the presence of Christ.' },

  // -- June (days 152-181) --
  { day: 152, text: 'Justin Martyr, a philosopher who became a Christian, wrote the earliest surviving description of a Sunday worship service.' },
  { day: 153, text: 'Marcellinus and Peter, martyred under Diocletian, were buried in the catacombs that became places of pilgrimage.' },
  { day: 154, text: 'Charles Lwanga and companions were martyred in Uganda in 1886, among the first African saints of the modern era.' },
  { day: 155, text: 'Boniface felled the sacred oak of Thor at Geismar, showing that the old gods had no power against the living God.' },
  { day: 156, text: 'Norbert of Xanten founded the Premonstratensian order, combining active ministry with a contemplative rule of life.' },
  { day: 157, text: 'Around this time, the grape harvest in Israel begins — Jesus said, "I am the true vine, and my Father is the gardener."' },
  { day: 158, text: 'The early church in Ephesus received Paul\'s letter urging them to "put on the whole armor of God."' },
  { day: 159, text: 'Columba of Iona left Ireland to found a monastery on a tiny Scottish island that became a beacon of learning.' },
  { day: 160, text: 'Barnabas, the "son of encouragement," sold his field to support the apostles. His generosity funded the early church\'s mission.' },
  { day: 161, text: 'Around this time, the summer solstice approaches — the longest day, a reminder that God set the sun and seasons in their courses.' },
  { day: 162, text: 'Anthony of Padua, known for his powerful preaching, once preached to fish when people refused to listen.' },
  { day: 163, text: 'Elisha of the Old Testament struck the Jordan and it parted — God\'s power does not diminish from one generation to the next.' },
  { day: 164, text: 'The early church debated the nature of Christ at Chalcedon in 451, affirming Him as fully God and fully human.' },
  { day: 165, text: 'Around this time, Israelite farmers watched for the hot eastern wind (hamsin) that could wither crops overnight.' },
  { day: 166, text: 'The desert fathers taught that stillness (hesychasm) is not emptiness but attentiveness to the presence of God.' },
  { day: 167, text: 'Around the summer solstice, John the Baptist is remembered — he must increase, but I must decrease (John 3:30).' },
  { day: 168, text: 'Irenaeus of Lyon wrote "Against Heresies," the most important early defense of orthodox Christian teaching.' },
  { day: 169, text: 'Peter and Paul, pillars of the early church, are celebrated together — one the apostle to the Jews, the other to the Gentiles.' },
  { day: 170, text: 'The First Martyrs of Rome, killed under Nero in 64 AD, gave witness in the arena that launched centuries of faith.' },
  { day: 171, text: 'Around this time, the full heat of summer settles over the Holy Land. Psalm 121 promises shade at one\'s right hand.' },
  { day: 172, text: 'Oliver Plunkett, the last Catholic martyr at Tyburn, forgave his executioners from the scaffold.' },
  { day: 173, text: 'Thomas the Apostle, called "Doubting Thomas," later traveled to India and founded one of the world\'s oldest churches.' },
  { day: 174, text: 'Elizabeth of Portugal used her royal position to negotiate peace between warring kingdoms — a ministry of reconciliation.' },
  { day: 175, text: 'Anthony Zaccaria founded the Barnabite order, focused on revitalizing parishes through devotion and preaching.' },
  { day: 176, text: 'Maria Goretti, martyred at age 11, forgave her attacker — a radical witness to mercy that shook Italy.' },
  { day: 177, text: 'In July heat, ancient travelers rested under terebinth trees — Abraham met three visitors under the oaks of Mamre.' },
  { day: 178, text: 'Around this time, the fig harvest begins in Israel. Micah 4:4 envisions peace: "Everyone will sit under their own fig tree."' },
  { day: 179, text: 'Augustine of Hippo taught that our hearts are restless until they rest in God — a truth echoed across centuries.' },
  { day: 180, text: 'Benedict of Nursia wrote his Rule around 530 AD, shaping Western monasticism with balance of prayer, work, and rest.' },
  { day: 181, text: 'Henry II, Holy Roman Emperor, used his power to reform the church and fund monasteries across Europe.' },

  // -- July (days 182-212) --
  { day: 182, text: 'Kateri Tekakwitha, the first Native American saint, lived a life of prayer and service in 17th-century New York.' },
  { day: 183, text: 'Bonaventure, the "Seraphic Doctor," wrote that "the best theologian is not the one who reads the most but who loves the most."' },
  { day: 184, text: 'Our Lady of Mount Carmel — the Carmelite tradition teaches contemplative prayer as the heart of Christian life.' },
  { day: 185, text: 'Around this time, the grape harvest in biblical Israel reaches its peak. Jesus chose wine as a symbol of His blood.' },
  { day: 186, text: 'Camillus de Lellis, a former soldier and gambler, founded an order dedicated to caring for the sick.' },
  { day: 187, text: 'In the heat of summer, the Psalms of Ascent (120-134) were sung by pilgrims traveling uphill to Jerusalem.' },
  { day: 188, text: 'Around this date, the early church remembered Elijah\'s confrontation on Mount Carmel — "How long will you waver between two opinions?"' },
  { day: 189, text: 'Lawrence of Brindisi, a Capuchin linguist, preached in nearly every European language, breaking down barriers for the gospel.' },
  { day: 190, text: 'Mary Magdalene was the first witness of the resurrection — the gospel was first proclaimed by a woman.' },
  { day: 191, text: 'Bridget of Sweden received visions of the Passion that shaped medieval devotion to the sufferings of Christ.' },
  { day: 192, text: 'Sharbel Makhluf, a Lebanese hermit, spent years in silence and prayer. His tomb became a site of reported healings.' },
  { day: 193, text: 'James the Greater, brother of John, was the first apostle martyred — beheaded by Herod Agrippa in Acts 12.' },
  { day: 194, text: 'Joachim and Anne, grandparents of Jesus, are honored — family faith passed across generations.' },
  { day: 195, text: 'Around this time, the threshing floors of ancient Israel were busy separating wheat from chaff — an image Jesus used for judgment.' },
  { day: 196, text: 'The Sleeping Disciples: in Gethsemane, even Jesus\' closest friends could not stay awake. Grace covers our weakness.' },
  { day: 197, text: 'Martha of Bethany served Jesus with practical hospitality. Both contemplation and action have a place in the Christian life.' },
  { day: 198, text: 'Peter Chrysologus, bishop of Ravenna, preached short but powerful homilies — proof that brevity can carry great weight.' },
  { day: 199, text: 'Ignatius of Loyola founded the Jesuits with the motto "Ad Majorem Dei Gloriam" — for the greater glory of God.' },
  { day: 200, text: 'Alphonsus Liguori founded the Redemptorists and wrote extensively on moral theology and the spiritual life.' },
  { day: 201, text: 'Eusebius of Vercelli was exiled for defending the divinity of Christ — he endured imprisonment rather than compromise.' },
  { day: 202, text: 'Around this time, summer heat tests the patience of farmers awaiting autumn rain. James 5:7 counsels patient endurance.' },
  { day: 203, text: 'The Curé of Ars, John Vianney, spent 16 hours a day hearing confessions, transformed a village through pastoral love.' },
  { day: 204, text: 'The Dedication of the Basilica of St. Mary Major recalls how early Christians honored Mary as Theotokos, the God-bearer.' },
  { day: 205, text: 'The Transfiguration: on a high mountain, Peter, James, and John saw Jesus\' glory revealed — a foretaste of eternity.' },
  { day: 206, text: 'Sixtus II and companions were martyred while celebrating the Eucharist in the catacombs during the Valerian persecution.' },
  { day: 207, text: 'Dominic founded the Order of Preachers, believing that well-trained teachers could combat error better than swords.' },
  { day: 208, text: 'Mary Sumner founded the Mothers\' Union in 1876, believing that the Christian home is the foundation of a healthy society.' },
  { day: 209, text: 'Lawrence, a deacon in Rome, was asked to hand over the church\'s treasures. He presented the poor and said, "These are the treasures."' },
  { day: 210, text: 'Clare of Assisi left a wealthy family to follow Francis\'s example of poverty and prayer. Her community endures 800 years later.' },
  { day: 211, text: 'Around this time, the Perseid meteor showers fill the night sky — "The heavens declare the glory of God" (Psalm 19:1).' },
  { day: 212, text: 'Maximilian Kolbe volunteered to die in place of a stranger at Auschwitz — "Greater love has no one than this."' },

  // -- August (days 213-243) --
  { day: 213, text: 'Pontian and Hippolytus, once adversaries, were reconciled during their shared exile — proof that persecution can unite believers.' },
  { day: 214, text: 'The Assumption of Mary is celebrated — the early church believed God honored the mother of Jesus by taking her to heaven.' },
  { day: 215, text: 'Stephen of Hungary established Christianity as the state religion, building churches and inviting missionaries.' },
  { day: 216, text: 'Around this time, the olive harvest begins in Israel — olive oil was used for anointing, healing, and light in the Temple.' },
  { day: 217, text: 'John Eudes promoted devotion to the Sacred Hearts of Jesus and Mary, emphasizing God\'s tender love for humanity.' },
  { day: 218, text: 'Bernard of Clairvaux, the "honey-tongued doctor," reformed monastic life and preached with extraordinary eloquence.' },
  { day: 219, text: 'Pius X encouraged frequent Communion and lowered the age for First Communion, making the Eucharist accessible to children.' },
  { day: 220, text: 'The Queenship of Mary is celebrated — in ancient Israel, the queen mother (gebirah) held a position of honor and intercession.' },
  { day: 221, text: 'Rose of Lima was the first person born in the Americas to be canonized — holiness knows no geographic boundary.' },
  { day: 222, text: 'Bartholomew the Apostle is traditionally credited with bringing the gospel to Armenia, one of the first Christian nations.' },
  { day: 223, text: 'Louis IX of France is remembered as a just king who washed the feet of beggars and personally served in hospitals.' },
  { day: 224, text: 'Around this time, the late summer figs ripen in Israel — Amos was a "dresser of sycamore figs" before God called him to prophesy.' },
  { day: 225, text: 'Monica prayed for her son Augustine for decades before he converted — a testament to the power of persistent prayer.' },
  { day: 226, text: 'Augustine of Hippo, once a wayward youth, became one of the most influential theologians in Christian history.' },
  { day: 227, text: 'The Passion of John the Baptist — he was beheaded for speaking truth to Herod about his unlawful marriage.' },
  { day: 228, text: 'Around this time, farmers in ancient Israel stored grain for the coming winter — Joseph\'s wisdom in Egypt saved nations.' },
  { day: 229, text: 'The end of August brought the grape-treading season in Israel — Isaiah 63 uses it as an image of divine judgment.' },
  { day: 230, text: 'Aidan of Lindisfarne walked across northern England planting churches, speaking the gospel to all he met on the road.' },
  { day: 231, text: 'As summer wanes, the earth prepares for harvest. Galatians 6:9 encourages us: "Do not grow weary in doing good."' },
  { day: 232, text: 'Raymond Nonnatus was ransomed from captivity and dedicated his life to freeing other slaves — a ministry of liberation.' },
  { day: 233, text: 'Giles of Athens lived as a hermit in southern France, fed by a deer. Solitude with God bore fruit in unexpected ways.' },
  { day: 234, text: 'Gregory the Great sent missionaries to England and reformed church music — the Gregorian chant bears his name.' },
  { day: 235, text: 'Around this time, the Jewish month of Elul begins — a season of repentance and preparation before the High Holy Days.' },
  { day: 236, text: 'Teresa of Calcutta responded to a "call within a call," leaving her convent to serve the poorest of the poor.' },
  { day: 237, text: 'The Birth of the Blessed Virgin Mary — the early church celebrated this feast by the 5th century.' },
  { day: 238, text: 'Peter Claver ministered to enslaved Africans arriving in Colombia, declaring himself "slave of the slaves forever."' },
  { day: 239, text: 'Around this date, the Feast of Trumpets (Rosh Hashanah) approaches — the shofar calls Israel to repentance and renewal.' },
  { day: 240, text: 'The Name of Mary — in Hebrew, Miriam means "bitter sea" or "beloved," a name carried with grace through salvation history.' },
  { day: 241, text: 'John Chrysostom was exiled twice for his fearless preaching against corruption among the powerful.' },
  { day: 242, text: 'The Exaltation of the Holy Cross recalls how Helena, mother of Constantine, reportedly found the True Cross in Jerusalem.' },
  { day: 243, text: 'Our Lady of Sorrows — the church remembers Mary standing at the foot of the cross, her faith unbroken by grief.' },

  // -- September-October (days 244-304) --
  { day: 244, text: 'Cornelius and Cyprian, one a pope and one a bishop, both gave their lives for the faith during times of persecution.' },
  { day: 245, text: 'Robert Bellarmine, a Jesuit cardinal, engaged the intellectual challenges of the Reformation with scholarship and charity.' },
  { day: 246, text: 'Around this time, the Day of Atonement (Yom Kippur) draws near — the most solemn day in the Jewish calendar.' },
  { day: 247, text: 'Januarius, bishop of Benevento, was martyred during the Diocletian persecution. His faithfulness under pressure inspires.' },
  { day: 248, text: 'Andrew Kim Taegon and companions were martyred in Korea, founding a church that grew from persecution into millions.' },
  { day: 249, text: 'Matthew the tax collector left everything at a single word from Jesus: "Follow me." Obedience can be that immediate.' },
  { day: 250, text: 'Around this time, the Feast of Tabernacles (Sukkot) begins — Israel dwelt in booths remembering God\'s provision in the wilderness.' },
  { day: 251, text: 'The early church in Philippi, founded by Paul after a vision of a man from Macedonia, was known for their joyful generosity.' },
  { day: 252, text: 'Padre Pio bore the stigmata for fifty years, pointing thousands to confession and Eucharistic devotion.' },
  { day: 253, text: 'Around this time, the autumn equinox arrives — equal day and night, a reminder of God\'s balance woven into creation.' },
  { day: 254, text: 'Cosmas and Damian, twin physicians, treated the poor without charge, earning the title "the Holy Unmercenaries."' },
  { day: 255, text: 'Wenceslaus, Duke of Bohemia, was murdered by his brother for his Christian convictions — "Good King Wenceslaus" lives on in song.' },
  { day: 256, text: 'The archangels Michael, Gabriel, and Raphael appear throughout Scripture at turning points in salvation history.' },
  { day: 257, text: 'Jerome spent thirty years translating the Bible into Latin. He said, "Ignorance of Scripture is ignorance of Christ."' },
  { day: 258, text: 'Therese of Lisieux taught the "little way" — doing small things with great love. She died at 24 and changed the church.' },
  { day: 259, text: 'The Guardian Angels are honored — Psalm 91:11 says, "He will command his angels concerning you to guard you."' },
  { day: 260, text: 'Around this time, the olive press was busy in ancient Israel — "Gethsemane" means "oil press," where Jesus was crushed in prayer.' },
  { day: 261, text: 'Francis of Assisi embraced poverty, preached to birds, and saw all creation as a brother and sister in God.' },
  { day: 262, text: 'Faustina Kowalska recorded visions of Divine Mercy, giving the church a devotion centered on God\'s limitless compassion.' },
  { day: 263, text: 'Bruno of Cologne founded the Carthusians, one of the strictest contemplative orders, in the French Alps.' },
  { day: 264, text: 'Our Lady of the Rosary — the repetitive prayer of the rosary follows an ancient pattern of meditation on Scripture.' },
  { day: 265, text: 'Around this time, the last fruits are gathered before winter — the biblical concept of gleaning protected the poor (Ruth 2).' },
  { day: 266, text: 'Denis of Paris, the first bishop of the city, was martyred on Montmartre ("mount of martyrs").' },
  { day: 267, text: 'John XXIII convened the Second Vatican Council, calling the church to "open the windows and let in fresh air."' },
  { day: 268, text: 'Around this time, the autumn rains begin in Israel — "early rains" that soften the ground for planting.' },
  { day: 269, text: 'Callistus I, a former slave who became bishop of Rome, showed that God raises the humble to positions of leadership.' },
  { day: 270, text: 'Teresa of Avila reformed the Carmelite order and taught that prayer is "an intimate conversation with the One who loves us."' },
  { day: 271, text: 'Hedwig of Silesia used her wealth to build hospitals and monasteries, seeing stewardship as a sacred responsibility.' },
  { day: 272, text: 'Ignatius of Antioch, on his way to martyrdom in Rome, wrote, "I am the wheat of God, ground by the teeth of beasts."' },
  { day: 273, text: 'Luke the physician and Gospel writer was Paul\'s faithful travel companion — the only Gentile author in the New Testament.' },
  { day: 274, text: 'The North American Martyrs gave their lives bringing the gospel to indigenous peoples in 17th-century Canada.' },
  { day: 275, text: 'Around this time, plowing begins in Israel for the winter crops — Hosea 10:12 says, "Break up your fallow ground."' },
  { day: 276, text: 'John Paul II became pope in 1978, the first non-Italian pope in 455 years, with the words: "Be not afraid!"' },
  { day: 277, text: 'John of Capistrano rallied Christians during the siege of Belgrade, showing that faith can inspire courage in dark times.' },
  { day: 278, text: 'Anthony Mary Claret founded the Claretian missionaries, dedicated to preaching and publishing to spread the Word.' },
  { day: 279, text: 'Around this time, the Maccabean revolt is remembered — faithful Jews chose death over abandoning the Torah.' },
  { day: 280, text: 'Demetrius of Thessaloniki, a Roman soldier martyred for his faith, is one of the most venerated saints in Eastern Christianity.' },
  { day: 281, text: 'Around this time, the church year begins moving toward its conclusion — a season for reflection on last things.' },
  { day: 282, text: 'Simon and Jude, apostles who preached together in Persia, are honored as examples of faithful partnership in ministry.' },
  { day: 283, text: 'The early church remembered that Ezekiel\'s vision of dry bones coming to life pointed toward resurrection hope.' },
  { day: 284, text: 'Around this date, the early autumn chill reminds us of the transience of life — "teach us to number our days" (Psalm 90:12).' },

  // -- November (days 305-334) --
  { day: 285, text: 'All Saints Day — the church celebrates not only the famous saints but every faithful believer who has gone before.' },
  { day: 286, text: 'All Souls Day — the church prays for all the faithful departed, trusting in God\'s mercy beyond the grave.' },
  { day: 287, text: 'Martin de Porres, a biracial Dominican lay brother in Peru, served the poor and sick regardless of their background.' },
  { day: 288, text: 'Charles Borromeo reformed his diocese during the plague, personally visiting the sick and distributing his wealth.' },
  { day: 289, text: 'Around this time, the early rains have softened the soil of Israel. Seeds planted now will bear fruit in spring.' },
  { day: 290, text: 'The Dedication of the Lateran Basilica reminds us that the church is not a building but the people gathered in Christ\'s name.' },
  { day: 291, text: 'Leo the Great confronted Attila the Hun at the gates of Rome, appealing for peace with quiet authority.' },
  { day: 292, text: 'Martin of Tours, a Roman soldier, cut his cloak in half to share with a freezing beggar — and saw Christ in a vision that night.' },
  { day: 293, text: 'Josaphat Kuntsevych worked for unity between Eastern and Western Christians, and was martyred for his efforts.' },
  { day: 294, text: 'Frances Xavier Cabrini, the first American citizen to be canonized, founded hospitals and orphanages across the nation.' },
  { day: 295, text: 'Albert the Great, teacher of Thomas Aquinas, saw no conflict between science and faith — both reveal God\'s truth.' },
  { day: 296, text: 'Margaret of Scotland used her queenship to reform the church and care for the poor. She washed beggars\' feet daily.' },
  { day: 297, text: 'Elizabeth of Hungary gave away her royal provisions to feed the hungry — roses reportedly appeared in her basket.' },
  { day: 298, text: 'The Dedication of the Basilicas of Peter and Paul recalls the two pillars on which the church in Rome was built.' },
  { day: 299, text: 'Around this time, Advent approaches — the church begins its season of watching, waiting, and preparing for the Lord.' },
  { day: 300, text: 'The Presentation of Mary — tradition holds that the young Mary was dedicated to God at the Temple in Jerusalem.' },
  { day: 301, text: 'Cecilia, patron of musicians, sang in her heart to the Lord — music has been central to Christian worship since the beginning.' },
  { day: 302, text: 'Clement of Rome wrote to the Corinthians around 96 AD, one of the earliest non-biblical Christian documents we possess.' },
  { day: 303, text: 'Andrew the Apostle, brother of Peter, is traditionally the first disciple Jesus called. He is patron of Scotland and Russia.' },
  { day: 304, text: 'Around this time, the church lights the first Advent candle — hope kindled in the darkness of a waiting world.' },

  // -- December (days 305-335/366) --
  { day: 305, text: 'Charles de Foucauld lived among the Tuareg people of the Sahara, embodying silent witness through presence and prayer.' },
  { day: 306, text: 'Francis Xavier died off the coast of China in 1552, having brought the gospel to India, Malaysia, and Japan.' },
  { day: 307, text: 'John of Damascus wrote hymns and defended the use of icons, insisting that the Incarnation sanctified the material world.' },
  { day: 308, text: 'Around this time, the Festival of Lights (Hanukkah) may begin — Jesus attended this feast in John 10:22.' },
  { day: 309, text: 'Nicholas of Myra, the historical figure behind Santa Claus, was known for secretly providing dowries for poor families.' },
  { day: 310, text: 'Ambrose of Milan, once a governor, became a bishop by popular demand and baptized Augustine.' },
  { day: 311, text: 'The Immaculate Conception — the church teaches that Mary was prepared from the beginning to bear the Son of God.' },
  { day: 312, text: 'Juan Diego received the image of Our Lady of Guadalupe in 1531, transforming the faith of an entire continent.' },
  { day: 313, text: 'Around this time, the longest nights settle over the Northern Hemisphere — "The people walking in darkness have seen a great light."' },
  { day: 314, text: 'Our Lady of Guadalupe appeared to Juan Diego as a mestiza woman, showing that God identifies with every culture.' },
  { day: 315, text: 'Lucy of Syracuse, whose name means "light," is celebrated during the darkest days of the year.' },
  { day: 316, text: 'John of the Cross wrote about the "dark night of the soul" — spiritual dryness that paradoxically draws us closer to God.' },
  { day: 317, text: 'Around this time, the O Antiphons begin — ancient prayers calling Christ by His messianic titles: Wisdom, Lord, Root of Jesse.' },
  { day: 318, text: 'Around this time, the church sings "O Come, O Come, Emmanuel" — a hymn of longing that stretches back a thousand years.' },
  { day: 319, text: 'The early church in Bethlehem built a basilica over the grotto where tradition says Jesus was born.' },
  { day: 320, text: 'Around this time, the winter solstice arrives — the darkest day, after which the light begins to return.' },
  { day: 321, text: 'Peter Canisius, the "Second Apostle of Germany," wrote catechisms that taught the faith in clear, simple language.' },
  { day: 322, text: 'John of Kanty, a Polish professor, was known for walking barefoot to Rome four times as a sign of devotion.' },
  { day: 323, text: 'On the night before Christmas, the church gathers in anticipation — "for unto us a child is born."' },
  { day: 324, text: 'Christmas Day: the Word became flesh and dwelt among us. God entered the world as a helpless infant in a manger.' },
  { day: 325, text: 'Stephen, the first Christian martyr, saw heaven opened as he was stoned — forgiveness on his lips even in death.' },
  { day: 326, text: 'John the Apostle, "the one whom Jesus loved," is traditionally believed to be the only apostle who died of natural causes.' },
  { day: 327, text: 'The Holy Innocents — Herod\'s slaughter of the children of Bethlehem is one of Scripture\'s darkest passages.' },
  { day: 328, text: 'Thomas Becket was murdered in Canterbury Cathedral in 1170 for defending the church\'s independence from royal power.' },
  { day: 329, text: 'Around this time, the year draws to a close. Ecclesiastes 3:1 reminds us: "For everything there is a season."' },
  { day: 330, text: 'Sylvester I was bishop of Rome when Constantine legalized Christianity, ending nearly three centuries of persecution.' },

  // Extra days for months with 31 days and leap year padding (days 331-366)
  { day: 331, text: 'The shepherds returned from Bethlehem "glorifying and praising God for all the things they had heard and seen."' },
  { day: 332, text: 'Anna the Prophetess recognized the infant Jesus in the Temple, giving thanks that redemption had come to Jerusalem.' },
  { day: 333, text: 'The Magi followed a star across vast deserts — seekers of truth will always find their way to Christ.' },
  { day: 334, text: 'Simeon held the Christ child and prayed, "My eyes have seen your salvation" — faith rewarded at the end of a long wait.' },
  { day: 335, text: 'The early church celebrated the octave of Christmas, eight days of reflection on the mystery of the Incarnation.' },
  { day: 336, text: 'In the catacombs, early Christians carved anchors into stone — a symbol of hope anchored in the resurrection.' },
  { day: 337, text: 'The Didache taught new converts to fast on Wednesdays and Fridays, a practice many Christians observe to this day.' },
  { day: 338, text: 'Clement of Alexandria taught that Greek philosophy was a "schoolmaster to bring the Greeks to Christ."' },
  { day: 339, text: 'The early church father Origen devoted his life to studying and explaining Scripture, producing over six thousand works.' },
  { day: 340, text: 'Around this time, the church reflects on the year past and the year to come — God is the same yesterday, today, and forever.' },
  { day: 341, text: 'The Apostles\' Creed, one of the earliest summaries of Christian faith, united believers across diverse cultures.' },
  { day: 342, text: 'The Council of Nicaea in 325 AD affirmed that Jesus is "of one substance with the Father" — the foundation of Christian orthodoxy.' },
  { day: 343, text: 'Patrick\'s breastplate prayer: "Christ with me, Christ before me, Christ behind me, Christ in me."' },
  { day: 344, text: 'The early Christians in Thessalonica received Paul\'s encouragement to "rejoice always, pray continually, give thanks in all circumstances."' },
  { day: 345, text: 'The Tower of Babel scattered languages, but at Pentecost the Spirit reversed the curse and united all tongues.' },
  { day: 346, text: 'Abraham left Ur not knowing where he was going — faith sometimes means stepping forward without a map.' },
  { day: 347, text: 'The Psalms contain every human emotion — rage, joy, despair, wonder — offered honestly to God.' },
  { day: 348, text: 'The widow\'s mite: Jesus noticed the smallest gift given with the greatest sacrifice. God measures generosity by the heart.' },
  { day: 349, text: 'Noah built an ark on dry land. Sometimes obedience looks foolish to the world but faithful to God.' },
  { day: 350, text: 'Ruth chose loyalty over comfort: "Where you go I will go, and where you stay I will stay." Covenant love endures.' },
  { day: 351, text: 'David danced before the Ark with all his might — worship that costs nothing accomplishes nothing.' },
  { day: 352, text: 'Daniel prayed three times daily with his windows open, even when it meant the lion\'s den. Faithfulness is non-negotiable.' },
  { day: 353, text: 'Esther risked her life with the words, "If I perish, I perish." Courage born of faith can change the course of history.' },
  { day: 354, text: 'Nehemiah rebuilt the walls of Jerusalem while holding a weapon — faith and practical action go hand in hand.' },
  { day: 355, text: 'The early Christians greeted each other with "Maranatha" — "Come, Lord!" An ancient prayer for Christ\'s return.' },
  { day: 356, text: 'The Ethiopian eunuch was reading Isaiah on a desert road when Philip explained the gospel. God arranges divine appointments.' },
  { day: 357, text: 'Lydia, a dealer in purple cloth, was the first European convert. The gospel often enters new territories through commerce.' },
  { day: 358, text: 'Priscilla and Aquila taught Apollos "the way of God more accurately" — mature believers mentor the gifted.' },
  { day: 359, text: 'The church at Smyrna was poor but spiritually rich (Revelation 2:9). Wealth and faithfulness are not always correlated.' },
  { day: 360, text: 'The church at Philadelphia received no rebuke from Christ — only encouragement to hold fast to what they have.' },
  { day: 361, text: 'John on Patmos saw a new heaven and new earth — the ultimate promise that God will make all things new.' },
  { day: 362, text: 'The tree of life appears in the first and last books of the Bible — what was lost in Eden is restored in the New Jerusalem.' },
  { day: 363, text: 'The river of living water flows from the throne of God in Revelation 22 — an eternal fulfillment of Jesus\' promise in John 7:38.' },
  { day: 364, text: 'The twenty-four elders cast their crowns before the throne: all human achievement is offered back to the One who gave it.' },
  { day: 365, text: 'The final words of Scripture: "Come, Lord Jesus." The story of faith ends — and begins again — with longing for His presence.' },
  { day: 366, text: 'In a leap year, this extra day is a gift of time — a reminder that every moment is an opportunity to seek God\'s face.' },
];
